### ISSUE TITLE
섹션창에서 정보 입력중 리턴을 누르면 다음 라인이 안생김

### ISSUE THREAD

**Issue by honge6090** [ProjectInTheClass/SongNotes#17]
**To Reproduce**
1. 노트에서 새로운 섹션을 만든다
2. 센셕 정보창에서 입력을 시작한다
3. 리턴을 누른다
4. 키보드가 사라지고 더이상 입력이 불가한다.

***추카 버그 -> 칸을 초과하는 길이의 글을 입력하면 새로운 라인 생성이 안 되고 잘림. 

**Expected behavior**
리턴을 누르면 섹션 정보창에서 새로운 라인이 만들어져야한다. 

**Screenshots**

<p float="left">
  <img src="여기에 이미지 링크 삽입" width="200" />
</p>

**Additional context**

**Comment by ParkKyuIl** [comment]
제가 하겠습니다

**Comment by wooseokyourself** [comment]
현재 구현방식에서, 섹션에 가사를 작성하려면 섹션을 한 번 클릭해야 한다. 그러므로 차라리 섹션의 가사부분을 클릭하면
https://fluffy.es/facebook-draggable-bottom-card-modal-1/
여기에 나와있는 Draggable Bottom Card 형식으로 텍스트입력창이 나오고, 그 안에서 입력을 완료하면 섹션내용을 업데이트하는건 어떤지?
드래그를 통해 입력창 뷰의 확장이 가능하므로 유저의 입맛에 맞게 다른 섹션의 가사와 현재 입력중인 가사를 한 번에 볼 수도 있음
