### ISSUE TITLE
섹션 여러개를 미리 만들면 오류 발생하여 앱죽음

### ISSUE THREAD

**Issue by ParkKyuIl** [ProjectInTheClass/SongNotes#28]
**Describe the bug**

1. 예를들어 빈노트에 섹션을 미리 4개를 만들어놓고 시작하려 + 버튼을 4번 누르면 오류발생
2. 섹션테이블뷰를 다운 캐스팅하여 뉴섹션셀을 만들고자 할때 미리 만들어놓은 셀이 없으면 오류가 발생하는 것 같음.

**Expected behavior**

**Screenshots**

<p float="left">

<img width="875" alt="스크린샷 2020-08-07 오후 6 06 25" src="https://user-images.githubusercontent.com/48053210/89629400-b89c2d80-d8d8-11ea-9bac-a71f983d0c12.png">
" width="200" />
</p>

**Additional context**

**Comment by wooseokyourself** [comment]
- iOS에서 키보드는 탭바를 가림. 즉 에디팅모드에서는 탭바에있는 섹션추가 버튼을 클릭할 수 없음.
- 에디팅모드란 텍스트입력을 위해 키보드가 올라와있는 상태를 의미. 즉, 에디팅모드의 종료는 키보드가 내려가는 것과 동일한 의미.

그러나 Xcode에서 설정을 따로 안해주면, Xcode 시뮬레이터에서는 iOS의 키보드가 올라오지 않음. 
XCode 시뮬레이터에서 iOS 디바이스의 키보드 올리는 법: https://stackoverflow.com/questions/24420873/xcode-6-keyboard-does-not-show-up-in-simulator

**Comment by wooseokyourself** [comment]
에디팅모드가 끝나고 섹션이 제거되는 과정은 구현된 대로 진행되어야 함. 이거 말고 빈 섹션 에디팅모드일때 섹션을 슬라이드하여 제거 등에서도 동일한 증상이 나타남
