### ISSUE TITLE
README에 제 이름을 넣고싶어요

### ISSUE THREAD

**Issue by wooseokyourself** [ProjectInTheClass/SongNotes#4]
**Is your feature request related to a problem? Please describe.**
// A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
// A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
// A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
// Add any other context or screenshots about the feature request here.

<p float="left">
  <img src="이미지 삽입시 여기에 링크 넣기" width="200" />
</p>

**Comment by wooseokyourself** [comment]
이건 제가 한 번 해보겠습니다.

**Comment by ParkKyuIl** [comment]
제가 할게요

**Comment by wooseokyourself** [comment]
이건 해결되었으니까 종료하겠습니다
