### ISSUE TITLE
녹화된 녹음파일 이름 수정 기능

### ISSUE THREAD

**Issue by ParkKyuIl** [ProjectInTheClass/SongNotes#44]
녹화한 녹음파일의 이름을 수정하여 어떤 멜로디를 녹음 했는지 구분 할 수 있었으면 좋겠습니다.
![스크린샷 2020-08-18 오후 3 41 04](https://user-images.githubusercontent.com/48053210/90479177-3a0d7e80-e169-11ea-8e9c-3902067f0931.png)

**Comment by wooseokyourself** [comment]
녹음파일에 대한 정보는 섹션할당으로도 충분하지 않을까?? 내 예상으로 유저는 보통 자기가 쓴 가사를 보면서 멜로디 몇개를 흥얼거렸다가 괜찮다 싶으면 녹음할거고, 그게 의미있으면 해당 섹션으로 바로 할당하기 때문에 녹음파일의 제목설정은 왠지 있어도 안 쓸것 같은데...
