### ISSUE TITLE
Section 삭제기능 필요

### ISSUE THREAD

**Issue by ParkKyuIl** [ProjectInTheClass/SongNotes#8]
![스크린샷 2020-08-02 오후 10 54 02](https://user-images.githubusercontent.com/48053210/89124577-1284a800-d513-11ea-9091-ba7a7c2f75d2.png)

삭제 기능 구현 필요

**Comment by wooseokyourself** [comment]
노트의 슬라이드 제거처럼 섹션셀도 슬라이드해서 제거할거라면, NoteTableViewController.swift 의 94번째 줄에 있는  

`override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath)`  

함수 참고 추천. 이 함수가 노트를 제거하는 함수임. 이와 동일한 함수를 NoteViewController.swift 의 `SectionTable` 클래스에 추가하고 프로퍼티의 `sections`를 제거하도록 구현하면 될듯
